services:
  - type: web
    name: url-shortener
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: url-shortener-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: url-shortener-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: url-shortener-postgres
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_CACHE_TYPE
        value: redis
      - key: SPRING_DATA_REDIS_HOST
        fromService:
          type: redis
          name: url-shortener-redis
          property: host
      - key: SPRING_DATA_REDIS_PORT
        fromService:
          type: redis
          name: url-shortener-redis
          property: port
      - key: APP_BASE_URL
        value: https://url-shortener.onrender.com

  - type: redis
    name: url-shortener-redis
    plan: free
    ipAllowList: []

databases:
  - name: url-shortener-postgres
    databaseName: urlshortener
    user: url_user
    plan: free
